---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible 'molecule==2.7.0' 'docker<3.0.0'
script:
  - molecule lint
  - molecule create
  - molecule converge
  - molecule verify
  - molecule idempotence
  - molecule destroy
