---
- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip
    - python-setuptools

- name: install jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/local/bin/jq
    mode: 0755

- name: install pip
  easy_install:
    name: pip

- name: install awscli
  pip:
    name: awscli
  become: "True"
